[package]
name = "dlfile"
version = "0.1.0"
edition = "2021"

[dependencies]
openssl = { version = "0.10.68", features=["vendored"] }
reqwest = { version = "0.11", features = ["blocking", "json"] }
url = "2.5.4"
